//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafio_CRUD_CSharp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuarios
    {
        public int IdUsuario { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo Nome é obrigatório!")]
        [StringLength(100, ErrorMessage = "O nome deve possuir no máximo 100 caracteres")]
        public string Nome { get; set; } 
        public string Empresa { get; set; }
        public string Email { get; set; }
        public Nullable<long> TelefonePessoal { get; set; }
        public Nullable<long> TelefoneComercial { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    }
}
