//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafio_CRUD_CSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int IdUsuario { get; set; }
        public string Nome { get; set; }
        public string Empresa { get; set; }

        internal static object Where(Func<object, bool> p)
        {
            throw new NotImplementedException();
        }

        public string Email { get; set; }
        public Nullable<long> TelefonePessoal { get; set; }
        public Nullable<long> TelefoneComercial { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public static int UsuarioId { get; internal set; }
    }
}
